# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieindex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(related_name='movies', to='movieindex.Tag'),
        ),
    ]
