# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieindex', '0002_auto_20161126_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'permissions': (('download_movie', 'Can download movie'), ('play_movie', 'Can play movie'))},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies', to='movieindex.Tag'),
        ),
    ]
