# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieindex', '0003_auto_20161209_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'permissions': (('download_movie', 'Can download movie'), ('play_movie', 'Can play movie'), ('tag_movie', 'Can tag movie'))},
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movieindex.Tag'),
        ),
    ]
