# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieindex', '0005_auto_20161210_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefolder',
            name='default_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movieindex.MovieCategory'),
            preserve_default=False,
        ),
    ]
