# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieindex', '0008_moviedownloadkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=200)),
                ('status', models.CharField(default='NEW', max_length=100)),
                ('progress', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
