# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieindex', '0009_workercommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
